/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingPartyRouteImport } from './routes/wedding-party'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWeatherRouteImport } from './routes/api/public/weather'

const WeddingPartyRoute = WeddingPartyRouteImport.update({
  id: '/wedding-party',
  path: '/wedding-party',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWeatherRoute = ApiPublicWeatherRouteImport.update({
  id: '/api/public/weather',
  path: '/api/public/weather',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/faq': typeof FaqRoute
  '/our-story': typeof OurStoryRoute
  '/registry': typeof RegistryRoute
  '/travel': typeof TravelRoute
  '/wedding-party': typeof WeddingPartyRoute
  '/api/public/weather': typeof ApiPublicWeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/faq': typeof FaqRoute
  '/our-story': typeof OurStoryRoute
  '/registry': typeof RegistryRoute
  '/travel': typeof TravelRoute
  '/wedding-party': typeof WeddingPartyRoute
  '/api/public/weather': typeof ApiPublicWeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/faq': typeof FaqRoute
  '/our-story': typeof OurStoryRoute
  '/registry': typeof RegistryRoute
  '/travel': typeof TravelRoute
  '/wedding-party': typeof WeddingPartyRoute
  '/api/public/weather': typeof ApiPublicWeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/details'
    | '/faq'
    | '/our-story'
    | '/registry'
    | '/travel'
    | '/wedding-party'
    | '/api/public/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/details'
    | '/faq'
    | '/our-story'
    | '/registry'
    | '/travel'
    | '/wedding-party'
    | '/api/public/weather'
  id:
    | '__root__'
    | '/'
    | '/details'
    | '/faq'
    | '/our-story'
    | '/registry'
    | '/travel'
    | '/wedding-party'
    | '/api/public/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailsRoute: typeof DetailsRoute
  FaqRoute: typeof FaqRoute
  OurStoryRoute: typeof OurStoryRoute
  RegistryRoute: typeof RegistryRoute
  TravelRoute: typeof TravelRoute
  WeddingPartyRoute: typeof WeddingPartyRoute
  ApiPublicWeatherRoute: typeof ApiPublicWeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wedding-party': {
      id: '/wedding-party'
      path: '/wedding-party'
      fullPath: '/wedding-party'
      preLoaderRoute: typeof WeddingPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/weather': {
      id: '/api/public/weather'
      path: '/api/public/weather'
      fullPath: '/api/public/weather'
      preLoaderRoute: typeof ApiPublicWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailsRoute: DetailsRoute,
  FaqRoute: FaqRoute,
  OurStoryRoute: OurStoryRoute,
  RegistryRoute: RegistryRoute,
  TravelRoute: TravelRoute,
  WeddingPartyRoute: WeddingPartyRoute,
  ApiPublicWeatherRoute: ApiPublicWeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
